name: Run AI Telegram Bot

on:
  push:
    branches:
      - main
  workflow_dispatch: # Позволяет запускать бота вручную кнопкой

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-data: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Telegram Bot
      run: python bot.py
